/**
 * @file Automatically generated by barrelsby.
 */

export * from './account.resolver';
export * from './acl.resolver';
export * from './auth.resolver';
export * from './category.resolver';
export * from './customer.resolver';
export * from './inquiry.resolver';
export * from './language.resolver';
export * from './order.resolver';
export * from './product.resolver';
export * from './rate.resolver';
export * from './setting.resolver';
export * from './user.resolver';
export * from './webpage.resolver';
